# Generated by Django 4.0.1 on 2022-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome'),
        ),
    ]
